[window]
opacity=0.85

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font Propo"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Propo"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Propo"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Propo"
style = "Regular"

