#!/usr/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

/usr/bin/lxqt-policykit-agent &
polybar example &
picom &

bspc monitor -d I II III IV

bspc config top_padding          -8
bspc config left_padding         -5
bspc config right_padding        -5
bspc config bottom_padding       -5

bspc config border_width         1
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh -d --randomize --bg-fill /usr/share/backgrounds/archlinux/

env GTK_THEME=Materia-dark-compact
setxkbmap es
